/**
 * Browser tools for an agent nobody launched specially (spec §4.8).
 *
 * A page attaches to a session that is *already running* — usually one where
 * someone typed `claude` an hour ago. Claude Code fixes its MCP servers at
 * launch and reads no environment variable for them, so `$TRING_MCP_CONFIG`
 * being in the shell's environment does nothing by itself: something has to put
 * it on the command line.
 *
 * Claude Code takes a server from exactly three places, and two of them are
 * other people's property. The project's own `.mcp.json` writes tring into
 * repositories it does not own and that the user then has to gitignore. The
 * global `~/.claude.json` loads this server into every claude on the machine,
 * inside tring or not, and survives the uninstall. That leaves `--mcp-config`,
 * and the only way to add a flag to a command the user types is to own the name
 * they type.
 *
 * So each session's PATH starts with a tring-owned directory holding one script
 * called `claude`, which execs the real one with the flag appended. Typing
 * `claude` in any tile — including the fifteen already running when the page was
 * attached — gets the browser tools, nothing outside a tring session changes,
 * and removing the state directory removes the shim.
 *
 * The script resolves the real claude at run time rather than being generated
 * with a baked path, because the PATH that matters is the one after the user's
 * rc files have run: claude is commonly installed to a directory `.zshrc` adds,
 * or managed by a version manager that rewrites PATH per shell. The daemon's own
 * PATH is not that PATH. Windows is the exception and is documented where it is
 * made.
 */

import { constants, existsSync } from 'node:fs'
import { access, chmod, mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'

/** The agent whose name tring takes over. */
export const SHIMMED = 'claude'

/**
 * Dropped in the shim directory so the script can recognise that directory in
 * its own PATH without matching on its name.
 *
 * String-comparing PATH entries against the script's own path is what the
 * obvious version does, and it is wrong for a symlinked directory, a trailing
 * slash, or a relative entry — and being wrong means the script finds itself,
 * execs itself, and forks until the process table gives out. A file that only
 * this directory contains is true under every spelling.
 */
export const MARKER = '.tring-shim'

/**
 * Subcommands that parse their own options, where `--mcp-config` is not one of
 * them and would be a usage error rather than an ignored extra.
 */
const SUBCOMMANDS = [
  'mcp', 'config', 'doctor', 'update', 'install', 'migrate-installer',
  'setup-token', 'plugin', 'agents', 'sandbox',
]

/**
 * The POSIX shim.
 *
 * Built out of shell builtins and nothing else. An external command here — even
 * `dirname` — is a command that can be missing from a PATH the user has pruned,
 * and every failure in this script degrades towards running itself again.
 *
 * Every branch that is not certain runs claude exactly as it was typed. An agent
 * missing a tool can be told to try again; a `claude` that will not start has
 * taken the user's terminal away, and this script is on the PATH of every
 * session whether a browser is attached or not.
 */
export function posixShim(): string {
  return `#!/bin/sh
# Generated by tring at daemon start (see packages/server/src/agent-shim.ts).
# Runs the real Claude Code with this session's browser tools attached, so a
# page can be attached to a shell that was already running (spec 4.8).
# Safe to delete: tring rewrites it next time it starts.

# Find claude the way the shell would have, skipping any tring shim directory.
# Builtins only, and no test that a stripped-down PATH can make fail: the way
# this goes wrong is by finding itself, and it only has to go wrong once.
real=''
saved_ifs=$IFS
IFS=:
for dir in $PATH; do
	[ -n "$dir" ] || dir=.
	[ -f "$dir/${MARKER}" ] && continue
	if [ -f "$dir/${SHIMMED}" ] && [ -x "$dir/${SHIMMED}" ]; then
		real=$dir/${SHIMMED}
		break
	fi
done
IFS=$saved_ifs

if [ -z "$real" ]; then
	echo 'tring: ${SHIMMED} is not installed on this PATH' >&2
	exit 127
fi

# From here down, the only question is whether to add the flag.
add=yes
[ -n "\${TRING_MCP_CONFIG:-}" ] && [ -f "\${TRING_MCP_CONFIG:-}" ] || add=no
case \${1:-} in
${SUBCOMMANDS.join('|')}) add=no ;;
esac
# Someone who passed their own --mcp-config gets theirs, not ours on top of it.
for arg do
	case $arg in
	--mcp-config|--mcp-config=*) add=no ;;
	esac
done

[ "$add" = yes ] && exec "$real" --mcp-config "$TRING_MCP_CONFIG" "$@"
exec "$real" "$@"
`
}

/**
 * The Windows shim, generated with an absolute path to the real claude.
 *
 * Resolved here rather than scanned in the script for the reason the POSIX one
 * scans: correctness follows the shell. A PowerShell profile does not reshape
 * PATH the way a `.zshrc` routinely does, and batch cannot walk a PATH
 * containing quoted entries without getting it wrong in ways that are quiet.
 * A baked path that is checked before use fails visibly if it ever goes stale.
 */
export function windowsShim(real: string): string {
  const guards = SUBCOMMANDS.map((s) => `if /i "%~1"=="${s}" goto plain`).join('\r\n')
  return [
    '@echo off',
    'rem Generated by tring at daemon start (see packages/server/src/agent-shim.ts).',
    "rem Runs the real Claude Code with this session's browser tools attached,",
    'rem so a page can be attached to a shell that was already running (spec 4.8).',
    'setlocal',
    `set "TRING_REAL=${real}"`,
    'if not exist "%TRING_REAL%" goto plain',
    'if "%TRING_MCP_CONFIG%"=="" goto plain',
    'if not exist "%TRING_MCP_CONFIG%" goto plain',
    guards,
    '"%TRING_REAL%" --mcp-config "%TRING_MCP_CONFIG%" %*',
    'exit /b %ERRORLEVEL%',
    ':plain',
    '"%TRING_REAL%" %*',
    'exit /b %ERRORLEVEL%',
    '',
  ].join('\r\n')
}

/** Where a PATH entry would have to hold `name` for the shell to run it. */
async function findOnPath(name: string, skip: string): Promise<string | null> {
  const dirs = (process.env['PATH'] ?? '').split(path.delimiter)
  // What Windows appends when a command is typed without an extension. A shim
  // that resolved `claude` to the extensionless launcher script would exec
  // something cmd cannot run.
  const exts = process.platform === 'win32'
    ? (process.env['PATHEXT'] ?? '.COM;.EXE;.BAT;.CMD').split(';')
    : ['']
  for (const dir of dirs) {
    if (!dir || path.resolve(dir) === path.resolve(skip)) continue
    // A second shim directory, from a tring that ran before this one or from a
    // different install. Resolving to one would bake a loop into the .cmd.
    if (existsSync(path.join(dir, MARKER))) continue
    for (const ext of exts) {
      const candidate = path.join(dir, name + ext)
      try {
        await access(candidate, constants.X_OK)
        return candidate
      } catch {
        // Not here, or not runnable. Keep walking the PATH.
      }
    }
  }
  return null
}

/**
 * Write the shim directory and return its path, or null if this platform or
 * this machine cannot have one.
 *
 * Null is not a failure worth surfacing: without a shim the Browser Agent tile
 * still launches an agent with the flag spelled out, which is what tring did
 * before. It costs a convenience, not a capability.
 */
export async function writeAgentShim(stateDir: string): Promise<string | null> {
  const dir = path.join(stateDir, 'bin')
  await mkdir(dir, { recursive: true })
  // Written before the shim, never after: between the two the directory is on
  // no PATH yet, but a shim that is findable before its marker is a shim that
  // can find itself.
  await writeFile(path.join(dir, MARKER), 'This directory holds tring shims.\n', 'utf8')

  if (process.platform === 'win32') {
    const real = await findOnPath(SHIMMED, dir)
    // No claude to wrap. Writing a shim that only ever prints "not installed"
    // would take the name away from an install that happens later.
    if (!real) return null
    await writeFile(path.join(dir, `${SHIMMED}.cmd`), windowsShim(real), 'utf8')
    return dir
  }

  const file = path.join(dir, SHIMMED)
  await writeFile(file, posixShim(), 'utf8')
  await chmod(file, 0o755)
  return dir
}

/**
 * Put `dir` first on the PATH in `env`, finding the variable however this
 * platform spells it — Windows environments carry `Path`, and a copied plain
 * object does not have `process.env`'s case-insensitive lookup.
 */
export function prependToPath(env: Record<string, string>, dir: string): void {
  const key = Object.keys(env).find((k) => k.toLowerCase() === 'path') ?? 'PATH'
  const current = env[key]
  env[key] = current ? `${dir}${path.delimiter}${current}` : dir
}
